[providers]
python = "3.11"

[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
dependsOn = ['setup']
cmds = ['pip install -r requirements.txt']

[phases.build]
dependsOn = ['install']

[start]
cmd = 'python weather_api.py'