import { FormData, WeatherData } from '@/types';

/**
 * Enhanced Share Handler for Fameline Luva
 * Provides Email + LinkedIn sharing with professional content
 */

// Helper function for application names
const getApplicationName = (formData: FormData): string => {
  const appMap = {
    'mission-critical': 'Mission Critical',
    'commercial-general': 'Commercial General',
    'industrial-warehouse': 'Industrial & Warehouse',
    'infrastructure': 'Infrastructure',
    'screening-aesthetic': 'Screening & Aesthetic',
    'specialized-acoustic': 'Specialized Acoustic'
  };
  return formData.louverApplication 
    ? appMap[formData.louverApplication as keyof typeof appMap]
    : formData.purpose?.replace('-', ' ') || 'General Application';
};

// Generate professional email content
const generateEmailContent = (
  formData: FormData, 
  weatherData: WeatherData | null,
  recommendedModel?: string
): { subject: string; body: string } => {
  const appName = getApplicationName(formData);
  
  const subject = `Fameline Luva AI Recommendation - ${formData.name || 'Project'} (${formData.location || 'Location TBD'})`;
  
  const body = `Dear Colleague,

I've completed a louver specification using Fameline Luva AI and wanted to share the results with you.

PROJECT DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Contact: ${formData.name || 'Not specified'}
• Location: ${formData.location || 'Not specified'}
• Application: ${appName}
• Environment: ${formData.environment || 'Not specified'}
${formData.buildingType ? `• Building Type: ${formData.buildingType}` : ''}
${formData.buildingHeight ? `• Building Height: ${formData.buildingHeight}` : ''}

${formData.airflowRequirement || formData.waterTolerance ? `
PERFORMANCE REQUIREMENTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${formData.airflowRequirement ? `• Airflow: ${formData.airflowRequirement}` : ''}
${formData.waterTolerance ? `• Water Tolerance: ${formData.waterTolerance}` : ''}
` : ''}

${weatherData ? `
CLIMATE ANALYSIS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Temperature: ${weatherData.temperature}°C
• Rainfall: ${weatherData.rainfall}mm
• Wind Speed: ${weatherData.windSpeed} m/s
• Wind Direction: ${weatherData.windDirection}°
` : ''}

${recommendedModel ? `
AI RECOMMENDATION:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ Recommended Model: ${recommendedModel}

This recommendation is based on advanced AI analysis considering environmental conditions, building specifications, performance criteria, and aesthetic preferences.
` : ''}

VIEW FULL DETAILS:
${window.location.href}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Fameline Luva AI - Smart Louver Selection
Leading architectural louver solutions across Asia Pacific

Best regards,
${formData.name || 'Fameline Luva User'}`;

  return { subject, body };
};

// Generate LinkedIn sharing content
const generateLinkedInContent = (
  formData: FormData,
  recommendedModel?: string
): string => {
  const appName = getApplicationName(formData);
  
  return `Just completed a comprehensive louver specification for ${formData.location || 'my project'} using Fameline Luva AI! 🏗️

The AI analysis considered:
✅ ${appName} requirements
✅ Environmental conditions & climate data  
✅ Building specifications & performance criteria
✅ Aesthetic preferences & design goals

${recommendedModel ? `AI Recommendation: ${recommendedModel}` : 'Smart AI-powered recommendation generated'}

Impressed by how technology is revolutionizing the building envelope specification process. The level of detail and accuracy in louver selection has never been more precise.

#Architecture #BuildingEnvelope #HVAC #Construction #AI #SmartBuilding #Louvers #FamelineAPSG`;
};

/**
 * Main simplified share function - Email + LinkedIn only
 */
export const handleEnhancedShare = async (
  formData: FormData, 
  weatherData: WeatherData | null,
  recommendedModel?: string
): Promise<{ success: boolean; method: string }> => {
  // Try Web Share API first (mobile & modern browsers)
  if (navigator.share) {
    try {
      await navigator.share({
        title: 'Fameline Luva AI Recommendation',
        text: `Louver specification for ${formData.location || 'project'} - ${recommendedModel || 'AI recommendation'}`,
        url: window.location.href
      });
      return { success: true, method: 'native' };
    } catch (error) {
      console.log('Native sharing cancelled or failed:', error);
      // Fall through to custom modal
    }
  }

  // Show simplified share modal for desktop
  return showSimplifiedShareModal(formData, weatherData, recommendedModel);
};

/**
 * Simplified share modal - Email + LinkedIn only
 */
const showSimplifiedShareModal = (
  formData: FormData,
  weatherData: WeatherData | null,
  recommendedModel?: string
): Promise<{ success: boolean; method: string }> => {
  return new Promise((resolve) => {
    // Create modal overlay
    const overlay = document.createElement('div');
    overlay.style.cssText = `
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.8);
      backdrop-filter: blur(10px);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 10000;
      font-family: 'Poppins', sans-serif;
    `;

    // Create modal content
    const modal = document.createElement('div');
    modal.style.cssText = `
      background: linear-gradient(135deg, #064e3b, #065f46);
      border-radius: 16px;
      border: 1px solid rgba(255, 255, 255, 0.1);
      padding: 2rem;
      max-width: 400px;
      width: 90%;
      color: white;
      position: relative;
    `;

    modal.innerHTML = `
      <div style="text-align: center; margin-bottom: 1.5rem;">
        <h3 style="color: #10b981; margin: 0 0 0.5rem 0; font-size: 1.5rem;">Share Your Specification</h3>
        <p style="color: rgba(255, 255, 255, 0.8); margin: 0; font-size: 0.9rem;">Choose your preferred sharing method</p>
      </div>

      <div style="display: flex; flex-direction: column; gap: 0.75rem;">
        <!-- Email Button -->
        <button id="shareEmail" style="
          background: rgba(255, 255, 255, 0.1);
          border: 1px solid rgba(255, 255, 255, 0.2);
          color: white;
          padding: 1.25rem;
          border-radius: 8px;
          cursor: pointer;
          transition: all 0.3s ease;
          display: flex;
          align-items: center;
          gap: 1rem;
          font-size: 1rem;
          font-weight: 500;
          width: 100%;
        ">
          <span style="font-size: 1.5rem;">📧</span>
          <div style="text-align: left;">
            <div style="font-weight: 600;">Email Specification</div>
            <div style="font-size: 0.8rem; color: rgba(255, 255, 255, 0.7);">Professional email with full project details</div>
          </div>
        </button>

        <!-- LinkedIn Button -->
        <button id="shareLinkedIn" style="
          background: rgba(255, 255, 255, 0.1);
          border: 1px solid rgba(255, 255, 255, 0.2);
          color: white;
          padding: 1.25rem;
          border-radius: 8px;
          cursor: pointer;
          transition: all 0.3s ease;
          display: flex;
          align-items: center;
          gap: 1rem;
          font-size: 1rem;
          font-weight: 500;
          width: 100%;
        ">
          <span style="font-size: 1.5rem;">💼</span>
          <div style="text-align: left;">
            <div style="font-weight: 600;">Share on LinkedIn</div>
            <div style="font-size: 0.8rem; color: rgba(255, 255, 255, 0.7);">Professional networking post</div>
          </div>
        </button>
      </div>

      <button id="closeModal" style="
        position: absolute;
        top: 1rem;
        right: 1rem;
        background: none;
        border: none;
        color: rgba(255, 255, 255, 0.6);
        font-size: 1.5rem;
        cursor: pointer;
        width: 2rem;
        height: 2rem;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 50%;
        transition: all 0.3s ease;
      ">&times;</button>
    `;

    // Add hover effects
    const buttons = modal.querySelectorAll('button:not(#closeModal)');
    buttons.forEach(button => {
      button.addEventListener('mouseenter', () => {
        (button as HTMLElement).style.background = 'rgba(255, 255, 255, 0.2)';
        (button as HTMLElement).style.transform = 'translateY(-2px)';
      });
      button.addEventListener('mouseleave', () => {
        (button as HTMLElement).style.background = 'rgba(255, 255, 255, 0.1)';
        (button as HTMLElement).style.transform = 'translateY(0)';
      });
    });

    // Add event listeners
    modal.querySelector('#shareEmail')?.addEventListener('click', () => {
      const emailContent = generateEmailContent(formData, weatherData, recommendedModel);
      const subject = encodeURIComponent(emailContent.subject);
      const body = encodeURIComponent(emailContent.body);
      
      window.open(`mailto:?subject=${subject}&body=${body}`);
      closeModal();
      resolve({ success: true, method: 'email' });
    });

    modal.querySelector('#shareLinkedIn')?.addEventListener('click', () => {
      const url = encodeURIComponent(window.location.href);
      const text = encodeURIComponent(generateLinkedInContent(formData, recommendedModel));
      
      window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}&summary=${text}`, '_blank');
      closeModal();
      resolve({ success: true, method: 'linkedin' });
    });

    const closeModal = () => {
      document.body.removeChild(overlay);
    };

    modal.querySelector('#closeModal')?.addEventListener('click', () => {
      closeModal();
      resolve({ success: false, method: 'cancelled' });
    });

    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) {
        closeModal();
        resolve({ success: false, method: 'cancelled' });
      }
    });

    overlay.appendChild(modal);
    document.body.appendChild(overlay);
  });
};